
alias y="yarn"
alias ys="yarn serve"
alias yst="yarn start"
alias yd="yarn dev"
alias ns="npm start"
alias pip="pip3"
alias py="python3"
alias python="python3"
alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias scratch="cd ~/Things/scratch; code ."
alias dust="export FLASK_APP=server; export FLASK_ENV=development; pipenv run flask"
alias mongod="sudo mongod --dbpath /System/Volumes/Data/data/db"
alias breakpoints="echo 'xs: above 0 \nsm: above 576px \nmd: above 768px \nlg: above 992px \nxl: above 1200px \n'"
alias be="bundle exec"
alias ngs="ng serve"
alias ngt="ng test"
alias backend="cd ~/Things/houwzer/backend"
alias frontend="cd ~/Things/houwzer/frontend"
alias dbdump="~/Things/houwzer/util/db-dump"
alias proddb="DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rake db:drop db:create; psql houwzer-development < ~/Things/houwzer/util/production-dump.sql"
alias devdb="DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rake refresh:db"
alias migrate="bin/rails db:migrate RAILS_ENV=development"
alias cache="rails dev:cache"
alias delayjobs="be rake jobs:work"
alias clearjobs="be rake jobs:clear"
alias testdb="RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load db:seed"
alias dotfiles="cd ~/Things/dotfiles;  code ."
alias reload="source ~/.zshrc"
