alias y="yarn"
alias ys="yarn serve"
alias yst="yarn start"
alias yd="yarn dev"
alias ns="npm start"
alias pip="pip3"
alias py="python3"
alias python="python3"
alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias scratch="cd ~/Things/scratch; code ."
alias dust="export FLASK_APP=server; export FLASK_ENV=development; pipenv run flask"    
alias mongod="sudo mongod --dbpath /System/Volumes/Data/data/db"
